spring.application.name=citas-medicas

logging.level.root=INFO
logging.level.org.hibernate=DEBUG
logging.level.org.springframework=DEBUG

spring.datasource.url=jdbc:oracle:thin:@mibd_high
spring.datasource.username=fullstack1
spring.datasource.password=ClaseDuoc123-
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.properties.oracle.net.tns_admin=/app/wallet
spring.jpa.hibernate.ddl-auto=create

server.port=8080